version: 1.0.{build}
image: Visual Studio 2017 Preview
environment:
  APPVEYOR_RDP_PASSWORD: Ha5$vW
  access_token:
    secure: 7UWsR6399VCdfeYzFZJEpEZ7+IIg1PPhmuQhBRnWwPc=
install:
- ps: build/appveyor-install-dependencies.ps1
build_script:
- cmd: build/build-windows.bat
artifacts:
- path: out
deploy_script:
- ps: build\deploy-gitlab-pages.ps1
