
%%{init: {'theme': 'default', 'themeCSS': 'svg { background-color: white; }'}}%%

classDiagram
  
  class DataInstance["sdth:DataInstance"] {
    sdth:hasName
    sdth:derivedFrom()
    sdth:elaborationOf()
  }
  class Program["sdth:Program"] {
    sdth:hasName
     }

  class ProgramStep["sdth:ProgramStep"] {
    sdth:hasSourceCode
    sdth:hasSDTL
    sdth:hasProgramStep()
  } 
 class FileInstance["sdth:FileInstance"] {
    sdth:hasName
    sdth:derivedFrom()
    sdth:elaborationOf()
  }
  class DataframeInstance["sdth:DataframeInstance"] {
    sdth:hasName
    sdth:derivedFrom()
    sdth:elaborationOf()
  }

  class VariableInstance["sdth:VariableInstance"] {
    sdth:hasName 
    sdth:derivedFrom()
    sdth:elaborationOf()   
  }

  class TextInstance["sdth:TextInstance"] {
    sdth:hasName
    sdth:derivedFrom()
  }
  class ImageInstance["sdth:ImageInstance"] {
    sdth:hasName
    sdth:derivedFrom()
  }


 

 DataInstance --> VariableInstance  : subclass
 DataInstance --> DataframeInstance : subclass  
  DataInstance --> TextInstance : subclass
 DataInstance --> ImageInstance : subclass


 Program --> ProgramStep : hasProgramStep

 ProgramStep --> VariableInstance : usesVariable
 ProgramStep --> VariableInstance : ssignsVariable
 ProgramStep --> DataInstance : consumesData
 ProgramStep --> DataInstance : producesData
 ProgramStep --> FileInstance : loadsFile
 ProgramStep --> FileInstance : savesFile


 DataframeInstance --> VariableInstance : hasVariableInstance

 FileInstance --> VariableInstance : hasVariableInstance
%% DataInstance --> DataInstance : sdth_derivedFrom

%%   DataframeInstance --> DataframeInstance : sdth_derivedFrom
%%   DataframeInstance --> DataframeInstance : sdth_elaborationOf

%%   FileInstance --> FileInstance : sdth_derivedFrom
%%   FileInstance --> FileInstance : sdth_elaborationOf
%%  VariableInstance --> VariableInstance : sdth_derivedFrom
%% VariableInstance --> VariableInstance : sdth_elaborationOf

